name: Deploy Project to Microsoft Azure

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
  pull_request:
    branches: [ main ]
    types: [ closed ]


jobs:
  front:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Build Application
        working-directory: front
        run: npm install && npm run build
      - name: Move the package to docker dir
        working-directory: front/docker
        run: cp -r ../build .
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: a1349636970/news_project

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: front/docker
          push: true
          tags: front